spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:file:./data/weatherdatadb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    
logging:
  level:
    org.philbour: DEBUG

server:
  servlet:
    context-path: /weatherservice/api
    
springdoc:
  swagger-ui.path: /docs/swagger-ui
  api-docs.path: /docs